"""
S-04: The Balancer task curriculum stages (mutations).
"""

from __future__ import annotations

from typing import Any, Dict, List
import re


UNIFORM_SUFFIX = """
Environmental Anomalies Detected
Sensors indicate that this region exhibits non-standard physical properties.
While the following variables MIGHT have changed from the initial environment, NOT ALL of them will necessarily be mutated in any given task. You must use active interaction and environmental feedback to deduce which specific conditions apply:
 - Fragile Anchor Points: The central pivot joint has a strictly limited static torque capacity. Even minor structural imbalances or sudden impacts may cause the fulcrum to snap, leading to total collapse.
 - Lateral Wind Currents: Invisible horizontal air currents exert a persistent force on all bodies. You must account for the overturning torque generated by these currents by adjusting the vertical or horizontal distribution of mass.
 - Dynamic Loading (Dropped Load): The target mass may be dropped from a significant height rather than being static. This requires your structure to be resilient enough to absorb the kinetic energy of the impact without destabilizing.
 - Spatial Obstructions: Static structural barriers exist in the environment that block standard build paths. You must design your structure to navigate around these "no-build" zones.
 - Gravitational Fluctuations: Local gravity may differ from Earth-standard, affecting the weight of the load and your own components and the margin for error in your balance calculations.
 - Rotational Damping: Angular or rotational damping of bodies may have changed, affecting how quickly oscillations decay.
 - Precision Thresholds: The allowable angle for "balance" may differ from the default. Your design must achieve the required static equilibrium to succeed.
 - Mass Variations: The target load mass may vary from the standard, requiring precise counterweight calculations based on the lever principle.

Discovery via feedback: Your objective is to identify the underlying physical rules of this specific environment through trial and reasoning. Initial standard solutions may fail; analyze the failure mode (e.g., where a joint breaks or how a body moves) to infer the hidden constraints and adapt your design.
"""


def update_task_description_for_visible_changes(base_description: str, target_terrain_config: Dict[str, Any], base_terrain_config: Dict[str, Any]) -> str:
    """Update description for visible changes."""
    description = base_description
    
    # Update Load Mass
    base_mass = base_terrain_config.get("load_mass", 200.0)
    target_mass = target_terrain_config.get("load_mass", 200.0)
    if target_mass != base_mass:
        pattern = r"(- \*\*The Load\*\*: A heavy block \(mass: )(\d+\.?\d*)( kg\))"
        description = re.sub(pattern, f"\\g<1>{target_mass:.1f} kg (originally {base_mass:.1f} kg in the source environment)\\g<3>", description)

    # Update max angle deviation in task description when mutated
    base_angle = base_terrain_config.get("max_angle_deviation_deg", 10.0)
    target_angle = target_terrain_config.get("max_angle_deviation_deg", 10.0)
    if target_angle != base_angle:
        angle_pattern = r"(horizontal angle within ±)(\d+\.?\d*)( degrees\))( for \d+ seconds\.)"
        if re.search(angle_pattern, description):
            description = re.sub(
                angle_pattern,
                lambda m: f"{m.group(1)}{target_angle:.1f}{m.group(3)} (originally ±{base_angle:.1f} degrees in the source environment){m.group(4)}",
                description,
            )

    if target_terrain_config.get("drop_load"):
        description = description.replace(
            "It may automatically attach (weld) to your structure if any part of your design is built within 0.5m of (3, 5.5), OR it may be DROPPED from above.",
            "The load will be DROPPED from above at x=3.0. You must catch and balance it without it touching the ground."
        )
    return description


def update_success_criteria_for_visible_changes(base_success_criteria: str, target_terrain_config: Dict[str, Any], base_terrain_config: Dict[str, Any]) -> str:
    """Update success criteria for visible changes."""
    criteria = base_success_criteria
    if target_terrain_config.get("drop_load"):
        criteria = criteria.replace(
            "Successfully catch or connect to the heavy load at x=3.0.",
            "Successfully catch the falling load and prevent it from touching the ground."
        )
    
    base_angle = base_terrain_config.get("max_angle_deviation_deg", 10.0)
    max_angle = target_terrain_config.get("max_angle_deviation_deg", 10.0)
    if max_angle != base_angle:
        criteria = criteria.replace("within ±10 degrees", f"within ±{max_angle:.1f} degrees (originally ±{base_angle:.1f} degrees in the source environment)")
        
    return criteria


def get_s04_curriculum_stages() -> List[Dict[str, Any]]:
    """Returns ordering stage configs."""
    return [
        {
            "stage_id": "Stage-1",
            "title": "The Glass Pivot",
            "mutation_description": "The pivot joint is brittle and the load is heavier. Precise static balance is required.",
            "task_description_suffix": UNIFORM_SUFFIX,
            "terrain_config": {
                "force_pivot_joint": True,
                "fragile_joints": True, 
                "max_joint_torque": 2000.0, 
                "load_mass": 250.0,
                "max_angle_deviation_deg": 90.0,
            },
            "physics_config": {
                "gravity": (0, -10.0),
                "angular_damping": 20.0,
            },
        },
        {
            "stage_id": "Stage-2",
            "title": "The Gale Force",
            "mutation_description": "Massive lateral wind creates overwhelming overturning torque. Account for horizontal forces.",
            "task_description_suffix": UNIFORM_SUFFIX,
            "terrain_config": {
                "force_pivot_joint": True,
                "wind_active": True,
                "wind_force_multiplier": 100.0,
                "load_mass": 200.0,
                "max_angle_deviation_deg": 90.0,
            },
            "physics_config": {
                "angular_damping": 20.0,
            },
        },
        {
            "stage_id": "Stage-3",
            "title": "The High-G Labyrinth",
            "mutation_description": "Higher gravity and structural barriers test spatial reasoning and balance.",
            "task_description_suffix": UNIFORM_SUFFIX,
            "terrain_config": {
                "force_pivot_joint": True,
                "obstacle_active": True,
                "obstacles": [
                    [1.0, 0.5, 2.5, 1.5], 
                    [-2.5, -1.5, -1.0, -0.5],
                ],
                "load_mass": 250.0,
                "max_angle_deviation_deg": 90.0,
            },
            "physics_config": {
                "gravity": (0, -40.0),
                "angular_damping": 20.0,
            },
        },
        {
            "stage_id": "Stage-4",
            "title": "The Perfect Storm",
            "mutation_description": "Catch a falling load in a wind-swept, high-gravity environment with a fragile pivot.",
            "task_description_suffix": UNIFORM_SUFFIX,
            "terrain_config": {
                "force_pivot_joint": True, 
                "obstacle_active": True,
                "obstacles": [
                    [-0.5, 3.0, 0.5, 4.0],
                ],
                "wind_active": True,
                "wind_force_multiplier": 5.0,
                "drop_load": True,
                "load_mass": 200.0,
                "fragile_joints": True,
                "max_joint_torque": 500000.0, 
                "max_angle_deviation_deg": 90.0,
            },
            "physics_config": {
                "gravity": (0, -10.0),
                "angular_damping": 20.0,
            },
        },
    ]
