"""
Task-specific feedback generation for S-03: The Crane
"""
from typing import Dict, Any, List


def format_task_metrics(metrics: Dict[str, Any]) -> List[str]:
    """
    Format task-specific metrics for S-03: The Crane.
    Exposes horizontal reach and structural load metrics.
    """
    metric_parts = []
    
    # 1. Reach Metrics
    if 'max_reach' in metrics and 'target_reach' in metrics:
        mr = metrics['max_reach']
        tr = metrics.get('target_reach', 12.0)
        status = "✅" if mr >= tr else "❌"
        metric_parts.append(f"{status} **Maximum Horizontal Reach**: {mr:.2f}m (Target: {tr:.2f}m)")

    if 'min_tip_y' in metrics and 'min_tip_height' in metrics:
        mty = metrics['min_tip_y']
        mth = metrics.get('min_tip_height', -15.0)
        status = "✅" if mty >= mth else "❌"
        metric_parts.append(f"{status} **Tip Clearance Height**: {mty:.2f}m (Minimum: {mth:.1f}m)")

    # 2. Structural Integrity
    if 'anchor_broken' in metrics:
        status = "❌ BROKEN" if metrics['anchor_broken'] else "✅ INTACT"
        metric_parts.append(f"**Structural Anchor Cohesion**: {status}")

    if 'max_anchor_torque' in metrics and 'max_anchor_torque_limit' in metrics:
        mat = metrics['max_anchor_torque']
        mal = metrics.get('max_anchor_torque_limit', 100000000.0)
        status = "✅" if mat <= mal else "❌"
        metric_parts.append(f"{status} **Peak Anchor Connection Torque**: {mat:.1f} N·m (Yield Limit: {mal:.1f} N·m)")

    # 3. Load Metrics
    if 'load_hold_time' in metrics:
        metric_parts.append(f"**Primary Load Engagement Time**: {metrics['load_hold_time']:.2f}s")
    if 'load2_hold_time' in metrics:
        metric_parts.append(f"**Secondary Load Engagement Time**: {metrics['load2_hold_time']:.2f}s")

    if 'structure_mass' in metrics and 'max_structure_mass' in metrics:
        sm = metrics['structure_mass']
        msm = metrics.get('max_structure_mass', 15000.0)
        status = "✅" if sm <= msm else "❌"
        metric_parts.append(f"{status} **Total Structural Mass**: {sm:.2f}kg (Budget: {msm:.0f}kg)")

    return metric_parts


def get_improvement_suggestions(metrics: Dict[str, Any], score: float, success: bool, 
                                failed: bool, failure_reason: str = None, 
                                error: str = None) -> List[str]:
    """
    Generate actionable diagnostic warnings for S-03.
    Diagnoses bending moments and tipping failures.
    """
    suggestions = []
    reason_lower = str(failure_reason).lower() if failure_reason else ""

    if error:
        suggestions.append(">> DIAGNOSTIC: Engineering constraints violated.")
        return suggestions

    if failed:
        suggestions.append(f">> FAILURE MODE: {failure_reason}")
        
        if "reach" in reason_lower:
            suggestions.append("-> Diagnostic: Insufficient longitudinal extension. The distal end of the cantilever failed to traverse the required horizontal distance.")
        elif "tip sagged" in reason_lower or "height" in reason_lower:
            suggestions.append("-> Diagnostic: Terminal Sag. The bending moment generated by the cantilever length or the load exceeds the structural stiffness, leading to vertical deflection below the clearance limit.")
        elif "anchor" in reason_lower:
            suggestions.append("-> Diagnostic: Anchorage Failure. The reactive moment at the fulcrum has exceeded the system's structural yield capacity.")

    return suggestions
